build/bundle - recognize uninitialized dcp repos and don't use them

diff --git a/build/bundle b/build/bundle
--- a/build/bundle
+++ b/build/bundle
@@ -143,7 +143,15 @@ localConfig.dcpClientDestination = "${BUNDLE_TMP}/dist";
 console.log(JSON.stringify(localConfig));
 EOJS
 
-SKIP_SUDO_CHECK=1 DCP_LOCAL_CONFIG_EXTRAS="${BUNDLE_TMP}/local-config.incl" "${DCP_SRC}/install.sh" -NI ${DCP_INSTALL_FLAGS} dcp-client
+if [ ! -d "${DCP_SRC}/node_modules" ]; then
+  echo "Cannot find ${DCP_SRC}/node_modules. Please run ${DCP_SRC}/install.sh dcp-client" >&2
+  exit 97
+fi
+
+NO_LOG=1\
+SKIP_SUDO_CHECK=1\
+DCP_LOCAL_CONFIG_EXTRAS="${BUNDLE_TMP}/local-config.incl"\
+  "${DCP_SRC}/install.sh" -NI ${DCP_INSTALL_FLAGS} dcp-client
 
 EXIT_CODE="$?"
 if [ "$EXIT_CODE" != "0" ]; then
